**kpi verification with power bi**

In [3]:
import pandas as pd
import numpy as np

In [4]:
movement_df=pd.read_csv(r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\Prcoessed_data\movement_data.csv")
fact_od=pd.read_csv(r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\Prcoessed_data\fact_od.csv")
leg_table=pd.read_csv(r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\Prcoessed_data\leg_table.csv")
summary_table=pd.read_csv(r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\Prcoessed_data\od_summary.csv")

In [25]:
movement_df

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude,terminal,journey_key,event_date,event_hour,day_of_week,week_number,Location Code,Division (Normalized)
0,AAIU2002386,107048781,IMPORT,RAIL,JNPA,Bharat Mumbai Container Terminals (PSA),PORT OUT,2025-12-02 02:50:00,1,18.87029,73.00640,BMCT,AAIU2002386_107048781,2025-12-02,2,Tuesday,49,JNPA,JNPA Port
1,AAIU2002386,107048781,IMPORT,RAIL,JNPT,Jawahar Lal Nehru Port Mumbai Division,STATION CROSSED,2025-12-02 21:00:00,2,18.94590,72.99870,BMCT,AAIU2002386_107048781,2025-12-02,21,Tuesday,49,JNPT,Mumbai Division
2,AAIU2002386,107048781,IMPORT,RAIL,JSLE,Jasaichirle Jn. Mumbai Division,STATION CROSSED,2025-12-02 23:45:00,3,19.15260,73.09170,BMCT,AAIU2002386_107048781,2025-12-02,23,Tuesday,49,JSLE,Mumbai Division
3,AAIU2002386,107048781,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,2025-12-03 00:45:00,4,18.99092,73.12000,BMCT,AAIU2002386_107048781,2025-12-03,0,Wednesday,49,PNVL,Mumbai Division
4,AAIU2002386,107048781,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,2025-12-03 01:08:00,5,19.04000,73.11495,BMCT,AAIU2002386_107048781,2025-12-03,1,Wednesday,49,KLMG,Mumbai Division
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797125,ZXJU0837382,107295943,IMPORT,RAIL,BOK,BORKHEDI Nagpur Railway Division,STATION CROSSED,2025-12-04 14:13:00,85,20.86018,78.97445,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,BOK,Nagpur Division
797126,ZXJU0837382,107295943,IMPORT,RAIL,BTBR,Buti Bori Jn. Nagpur Division,STATION CROSSED,2025-12-04 14:20:00,86,20.92000,79.01000,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,BTBR,Nagpur Division
797127,ZXJU0837382,107295943,IMPORT,RAIL,GMG,GUMGAON Nagpur Railway Division,STATION CROSSED,2025-12-04 14:29:00,87,20.99360,79.03000,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,GMG,Nagpur Division
797128,ZXJU0837382,107295943,IMPORT,RAIL,KRI,KHAPRI Nagpur Railway Division,STATION CROSSED,2025-12-04 14:40:00,88,21.05000,79.05000,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,KRI,Nagpur Division
797129,ZXJU0837382,107295943,IMPORT,RAIL,PCPK,MULTI MODEL LOGISTIC PARK,STATION CROSSED,2025-12-04 14:56:00,89,28.44920,76.97180,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,PCPK,Nagpur Division

In [35]:

# total_container
total_containers =fact_od["cntr_no"].nunique()
print("total_container :",total_containers)


# total_od pair

total_od_pairs = len(fact_od)
print(f"Total OD Pairs: {total_od_pairs}")

# average journry time

avg_journey_time = fact_od["journey_hours"].mean()
print(f"Average Journey Time (Hours)  : {avg_journey_time:.2f}")


# average intermedite station

avg_intermediate = fact_od["intermediate_stations"].mean()
print(f"Average Intermediate Stations : {avg_intermediate:.2f}")

# top destination divison

top_destination = (
    fact_od
    .groupby("destination_name")["cntr_trxn_id"]
    .nunique()
    .sort_values(ascending=False)
)

print(f"Top Destination Division : {top_destination.index[0]}")
print(f"Container Count : {top_destination.iloc[0]}")

total_container : 27039
Total OD Pairs: 27047
Average Journey Time (Hours)  : 74.19
Average Intermediate Stations : 28.47
Top Destination Division : DAHANU ROAD Mumbai Central Railway Division
Container Count : 5244

In [7]:
# verify daily trend


daily_trend = (
     movement_df
    .groupby("event_date")["cntr_trxn_id"]
    .nunique()
    .reset_index(name="container_count")
)

print(daily_trend.head())

daily_trend.head()

   event_date  container_count
0  2025-11-23                1
1  2025-11-24               73
2  2025-11-25              361
3  2025-11-26              810
4  2025-11-27             1318

   event_date  container_count
0  2025-11-23                1
1  2025-11-24               73
2  2025-11-25              361
3  2025-11-26              810
4  2025-11-27             1318

In [8]:

# Verify the Origin-Destination summary table.


summary_table.head(10)

,origin,destination_division,container_count,average_journey_time,average_intermediate_stations
0,BMCT,Agra Division,34,64.22,49.09
1,BMCT,Ahmedabad Division,48,777.54,35.69
2,BMCT,Ajmer Division,1,473.98,4.00
3,BMCT,Allahabad Division,864,104.49,36.40
4,BMCT,Amritsar Division,24,152.88,28.54
5,BMCT,Bangalore Division,15,156.73,85.67
6,BMCT,Bhavnagar Division,15,692.51,37.20
7,BMCT,Bhopal Division,571,86.61,48.65
8,BMCT,Bhusawal Division,40,36.35,53.00
9,BMCT,Delhi Division,275,112.24,16.43

In [9]:
# top 10 destination
top_destination.head(10)

destination_name
DAHANU ROAD Mumbai Central Railway Division                       5244
VIRAR Mumbai Central Railway Division                             2667
MULTI MODEL LOGISTIC PARK                                         1821
SANAT NAGAR CONCOR SIDING Secunderabad division                   1746
CONCOR CONTAINER TERMINAL ANKLESHWAR Vadodara Railway Division    1423
CONCOR SIDING.MANDIDEEP Bhopal Railway Division                   1247
M/S Concor Green Field Pft Ratlam Division                        1153
BOISAR Mumbai Central Railway Division                            1029
Vasai Road Jn. Mumbai Central Division                            1019
DAULATABAD CONCOR SIDING Nanded division                           969
Name: cntr_trxn_id, dtype: int64

In [10]:

# Quick validation of the leg-level dataset.


print(f"Total Leg Records : {len(leg_table)}")
print(f"Unique Journeys   : {leg_table['journey_key'].nunique()}")

Total Leg Records : 30226
Unique Journeys   : 485

In [12]:
# verify speed

leg_table["speed_category"].value_counts()

speed_category
Slow        14868
Moderate    10700
Fast         4658
Name: count, dtype: int64

**key business insights as per assignment**

In [11]:
origin_summary = (fact_od.groupby("origin").agg(Container_Count=("cntr_trxn_id","nunique")).sort_values("Container_Count",ascending=False))

print(origin_summary)

        Container_Count
origin
BMCT              10460
GTI                6664
NSICT              4318
NSIGT              3030
NSFT               2436
NSDT                  4

In [12]:
top_destination = (
    fact_od.groupby("destination_name")
    .agg(Container_Count=("cntr_trxn_id","nunique"))
    .sort_values("Container_Count",ascending=False)
)

print(top_destination.head(10))

                                                    Container_Count
destination_name
DAHANU ROAD Mumbai Central Railway Division                    5244
VIRAR Mumbai Central Railway Division                          2667
MULTI MODEL LOGISTIC PARK                                      1821
SANAT NAGAR CONCOR SIDING Secunderabad division                1746
CONCOR CONTAINER TERMINAL ANKLESHWAR Vadodara R...             1423
CONCOR SIDING.MANDIDEEP Bhopal Railway Division                1247
M/S Concor Green Field Pft Ratlam Division                     1153
BOISAR Mumbai Central Railway Division                         1029
Vasai Road Jn. Mumbai Central Division                         1019
DAULATABAD CONCOR SIDING Nanded division                        969

In [13]:
division_summary = (
    fact_od.groupby("destination_division")
    .agg(Container_Count=("cntr_trxn_id","nunique"))
    .sort_values("Container_Count",ascending=False)
)

print(division_summary)

                       Container_Count
destination_division
Mumbai Division                  12103
Nagpur Division                   2555
Allahabad Division                2140
Secunderabad Division             1756
Bhopal Division                   1644
Vadodara Division                 1478
Ratlam Division                   1379
Delhi Division                    1123
Nanded Division                    969
Bangalore Division                 328
Jhansi Division                    272
Ahmedabad Division                 258
Konkan Division                    148
Jodhpur Division                   147
Bhusawal Division                  135
Jaipur Division                    106
Amritsar Division                   90
Moradabad Division                  82
Kharagpur Division                  81
Bhavnagar Division                  61
Agra Division                       48
Izzatnagar Division                 25
Sealdah Division                     4
Malda Division                       4
Chennai Division                     2
Kota Division                        2
Ambala Cantt Division                1
Ajmer Division                       1
Pune Division                        1

In [14]:
leg_table["speed_category"].value_counts()

speed_category
Slow        14868
Moderate    10700
Fast         4658
Name: count, dtype: int64

In [16]:
# intermedite station statical analysis
fact_od["intermediate_stations"].describe()

count    27047.000000
mean        28.472030
std         24.701599
min          1.000000
25%         10.000000
50%         14.000000
75%         44.000000
max        135.000000
Name: intermediate_stations, dtype: float64

In [18]:
slowest_lane = (fact_od.groupby(
        ["origin", "destination_division"]).agg(
        Avg_Journey_Hours=("journey_hours","mean"),
        Containers=("journey_key","count")).sort_values(
        "Avg_Journey_Hours",
        ascending=False ))

print(slowest_lane.head(10))

                              Avg_Journey_Hours  Containers
origin destination_division
GTI    Ambala Cantt Division        1245.800000           1
NSFT   Bhavnagar Division           1009.840000           2
GTI    Pune Division                 890.050000           1
NSFT   Ahmedabad Division            869.739167          36
NSICT  Ahmedabad Division            868.656000          15
NSIGT  Ahmedabad Division            782.285000           8
BMCT   Ahmedabad Division            777.538750          48
GTI    Jodhpur Division              772.833333           3
BMCT   Jodhpur Division              740.341136          88
NSFT   Jodhpur Division              739.896429          56

In [22]:
ncr = ["Delhi Division", "Ambala Division"]

ncr_terminal = (
    fact_od[
        fact_od["destination_division"].isin(ncr)
    ]
    .groupby("origin")
    .agg(
        Containers=("journey_key", "count"),
        Avg_Journey_Time=("journey_hours", "mean")
    )
    .sort_values("Containers", ascending=False)
)

print(ncr_terminal)

        Containers  Avg_Journey_Time
origin
GTI            490         98.890918
BMCT           275        112.239855
NSICT          150        124.475467
NSFT           104        124.498654
NSIGT          104        117.673462